import 'package:genkit/genkit.dart';
import 'package:genkit_google_genai/genkit_google_genai.dart';
import 'package:schemantic/schemantic.dart';
import 'schemas.dart';

/// Defines the `generateLesson` Genkit flow.
///
/// This flow uses Gemini with Google Search grounding to research a topic
/// and produce a structured lesson plan. It acts as the first stage in the
/// storify pipeline — its output feeds into the storybook generation step.
Flow getGenerateLessonFlow(Genkit ai) {
  return ai.defineFlow(
    name: 'generateLesson',
    // Schema types are generated by the `schemantic` package from schemas.dart.
    inputSchema: GenerateLessonRequest.$schema,
    outputSchema: SchemanticType.string(),
    fn: (input, _) async {
      final req = input as GenerateLessonRequest;

      // Use ai.generate() to call the Gemini model. The googleSearch config
      // enables Google Search grounding so the model can look up current facts.
      final response = await ai.generate(
        model: googleAI.gemini('gemini-2.5-flash'),
        config: GeminiOptions(
          googleSearch: GoogleSearch(),
        ),
        messages: [
          Message(
            role: Role.system,
            content: [
              TextPart(text: '''
You are an app that helps people understand complex concepts in a simple and fun way. The user has a question that they want explained in an engaging way. Your task is:

1. Search Google to get an accurate and grounded picture of the topic at hand.
2. Generate a "lesson plan" that accurately and approachably explains the core concepts of the lesson.
3. Break the lesson down into no more than 10 key ideas. Make sure to include details that could be turned into nice illustrations.
''')
            ],
          ),
          Message(
            role: Role.user,
            content: [TextPart(text: 'User question: ${req.question}')],
          ),
        ],
      );
      return response.text;
    },
  );
}

/// Defines the `cartoonify` Genkit flow.
///
/// Uses Gemini's image generation model to transform a user's photo into a
/// cartoon character. The cartoon is used as the user's avatar and can be
/// incorporated into story illustrations via the `illustrate` flow.
Flow getCartoonifyFlow(Genkit ai) {
  return ai.defineFlow(
    name: 'cartoonify',
    inputSchema: CartoonifyRequest.$schema,
    outputSchema: SchemanticType.string(),
    fn: (input, _) async {
      final req = input as CartoonifyRequest;

      // Send the user's photo to Gemini's image model with a text prompt
      // instructing it to create a cartoon version.
      final response = await ai.generate(
        model: googleAI.gemini('gemini-2.5-flash-image'),
        messages: [
          Message(
            role: Role.user,
            content: [
              TextPart(
                  text:
                      'Transform the person in the following image into a full-body cartoon character in a neutral pose. The background should be white.'),
              // MediaPart sends the image inline as a data URI.
              MediaPart(media: Media(url: req.image, contentType: 'image/jpeg')),
            ],
          )
        ],
      );
      if (response.media == null) {
        throw Exception("Image generation failed.");
      }
      // The generated cartoon is returned as a data URI.
      return response.media!.url;
    },
  );
}

/// Defines the `illustrate` Genkit flow.
///
/// Generates a single illustration for a storybook page. If a user image is
/// provided, the model uses it as a reference for drawing the user as a
/// character in the scene. Otherwise it generates the illustration without
/// a user character.
Flow getIllustrateFlow(Genkit ai) {
  return ai.defineFlow(
    name: 'illustrate',
    inputSchema: IllustrationRequest.$schema,
    outputSchema: SchemanticType.string(),
    fn: (input, _) async {
      final req = input as IllustrationRequest;

      final response = await ai.generate(
        model: googleAI.gemini('gemini-2.5-flash-image'),
        messages: [
          Message(
            role: Role.user,
            content: [
              // Only include the user's image if one was provided. When no
              // selfie is set, the illustration is generated without the user
              // character to avoid sending an empty/invalid image to the model.
              if (req.userImage != null && req.userImage!.isNotEmpty) ...[
                TextPart(text: '[USER]:\n'),
                MediaPart(media: Media(url: req.userImage!, contentType: 'image/jpeg')),
              ],
              TextPart(text: '''
You are illustrating a page in an educational storybook for a child. The story is about the question "${req.question}". Generate the illustration described below in a friendly cartoon style. ONLY illustrate exactly what is described below. The illustration should be colorful with full-image backgrounds.

${req.illustration}
'''),
            ],
          )
        ],
      );
      if (response.media == null) {
        throw Exception("Image generation failed.");
      }
      return response.media!.url;
    },
  );
}

/// Defines the `storify` Genkit flow.
///
/// This is the main orchestration flow that ties together multiple AI steps:
/// 1. Calls `generateLesson` to research the topic and create a lesson plan.
/// 2. Sends the lesson plan to Gemini to generate a structured storybook with
///    page text and illustration descriptions.
///
/// Uses Genkit's streaming support (`context.sendChunk`) to report progress
/// back to the client as each stage completes. The final output is a
/// [Storybook] with a title and list of pages.
Flow getStorifyFlow(Genkit ai) {
  // Compose flows: storify calls generateLesson internally.
  final generateLessonFlow = getGenerateLessonFlow(ai);

  return ai.defineFlow(
    name: 'storify',
    inputSchema: StorifyRequest.$schema,
    outputSchema: Storybook.$schema,
    // streamSchema enables streaming chunks back to the client.
    streamSchema: Storybook.$schema,
    fn: (input, context) async {
      final req = input as StorifyRequest;

      // Step 1: Generate a lesson plan using grounded search.
      context.sendChunk(Storybook(status: "Studying to prepare lesson..."));
      final lesson = await generateLessonFlow(
          GenerateLessonRequest(question: req.question));

      // Step 2: Generate the storybook from the lesson plan.
      // The outputSchema constrains the model to return structured JSON
      // matching the Storybook schema.
      context.sendChunk(Storybook(status: "Generating lesson storybook..."));
      final response = await ai.generate(
        model: googleAI.gemini('gemini-2.5-flash'),
        messages: [
          Message(
            role: Role.system,
            content: [
              TextPart(text: '''
You are an app that helps people understand complex concepts in a simple and fun way. The user has a question that they want explained in an engaging way. A lesson plan has already been generated and included below. Your task is to generate up to 5 pages of a simple "storybook lesson" that explains the subject. Each page should include 1-2 paragraphs and a detailed description of an illustration to accompany it.

Illustration descriptions will be generated using an image model starring the user as a cartoon character. Use `USER` in the image description to incorporate them in. For example: "USER is riding a jeep through the African Serengeti, pointing at a galloping herd of wildebeests." ONLY use `USER` in image descriptions, not in titles or page text. ONLY include the user when the image might need a stand-in for a person, many pages will not require it. Try to include USER in the first page's illustration.

Your explanations should be approachable, fun, and easy to understand. Write in a simple and clear manner an adult would like to read using concepts that are simple and universal. You should cover all of the most important parts of the topic but you need to keep it short - no more than 5 pages.

=== LESSON ===

$lesson
''')
            ],
          ),
          Message(
            role: Role.user,
            content: [TextPart(text: 'Generate the storybook.')],
          ),
        ],
        // outputSchema tells Genkit to parse the model's response as structured
        // JSON conforming to the Storybook schema.
        outputSchema: Storybook.$schema,
      );

      final book = response.output as Storybook;
      return Storybook(
        status: "Done",
        bookTitle: book.bookTitle,
        pages: book.pages,
      );
    },
  );
}
