name: eli5_dart
description: Genkit logic for eli5 dart project
publish_to: 'none'

environment:
  sdk: '>=3.6.0 <4.0.0'

dependencies:
  genkit: any
  genkit_google_genai: any
  genkit_shelf: any
  schemantic: any

dev_dependencies:
  build_runner: any
  lints: any
